theme: jekyll-theme-minimal
title: Crash Course on Command Line Basics
description: Upendra Bhattarai <br/>
              2023-11-01

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
